name: Generate Contribution Snake

on:
  # Run manually or every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ukazimchisom
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake to output branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout -B output
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update contribution snake"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ukazimchisom/ukazimchisom.git output
